onlinetutionmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from students import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tutionadmin/',include('tutionadmin.urls')),

    #-------------------- students---------------------
    path('', views.CourseListViews.as_view(), name='home'),
    path('detail/<int:pk>/', views.CourseDetailViews.as_view(), name='detail'),
]

tutionadmin/urls.py
from django.urls import path
from .import views
app_name='tutionadmin'
urlpatterns = [
    path('',views.login, name='login'),
    path('adminhome/', views.Adminhome, name='adminhome'),
    path('register/', views.register, name='register'),
    path('addcourse/',views.addcourse, name='addcourse'),
    path('logout/',views.logout, name='logout'),
    # path('update/<int:pk>/',views.update, name='update'),
    path('update/<int:pk>/', views.Update.as_view(), name='update'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

students/models.py
from django.db import models

# Create your models here.

tutionadmin/models.py
from django.db import models

# Create your models here.
class AddCourse(models.Model):
    courseid= models.AutoField(primary_key=True)
    course = models.CharField(max_length=60)
    faculty = models.CharField(max_length=50)
    date =models.DateField()
    time = models.CharField(max_length=20)
    fee = models.IntegerField()
    duration = models.CharField(max_length=20)


    def __str__(self):
        return self.course

class MainAdminRegister(models.Model):
    admin_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=60)

    def __str__(self):
        return self.username

tutionadmin/forms.py
from django import forms
from django.core.exceptions import ValidationError
import re


from .models import AddCourse, MainAdminRegister


class AddCourseForm(forms.ModelForm):
    class Meta:
        model = AddCourse
        fields = '__all__'

    def clean_fee(self):
        fee = self.cleaned_data['fee']
        if fee >= 3000:
            return fee
        else:
            raise ValidationError('Fee must be greater than 3000..')

    def clean_name(self):
        name1 = self.cleaned_data['name'].title()
        name = re.findall(r'^[A-Za-z]*$', name1)
        return name


class MainAdminRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=60, widget=forms.PasswordInput)
    class Meta:
        model = MainAdminRegister
        fields = '__all__'

    def clean_username(self):
        username = self.cleaned_data['username'].title()
        if len(username)>=3:
            return username
        else:
            raise ValidationError('Username must be more than 2 alphabets' )

    def clean_password(self):
        password= self.cleaned_data['password']
        if len(password)>=8:
            return password
        else:
            raise ValidationError('password must be more than 8 characters')


class AdminLoginForm(forms.Form):
    username = forms.CharField(min_length=4)
    password = forms.CharField(min_length=8, widget=forms.PasswordInput)

students/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from tutionadmin.models import AddCourse
# Create your views here.
class CourseListViews(ListView):
    model = AddCourse
    template_name = 'home.html'

class CourseDetailViews(DetailView):
    model = AddCourse
    template_name = 'course_detail_view.html'

tutionadmin/views.py
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import check_password, make_password
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

from .forms import AddCourseForm, MainAdminRegisterForm, AdminLoginForm
from django.contrib.messages import success
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import MainAdminRegister, AddCourse
from django.views.generic import UpdateView, DeleteView


# @login_required(login_url='/tutionadmin:login/')
def addcourse(request):
    form = AddCourseForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('tutionadmin:adminhome')
        else:
            redirect('tutionadmin:addcourse')
    else:
        form = AddCourseForm()
    return render(request, 'tutionadmin/registercourse.html', {'form': form})


def login(request):
    form = AdminLoginForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username').title()
        password = request.POST.get('password')
        adminname = get_object_or_404(MainAdminRegister, username=username)
        if adminname:
            flag = check_password(password, adminname.password)
            if flag:
                # request.session['member_id'] = adminname.id
                return redirect('tutionadmin:adminhome')
            else:
                raise ValidationError('Enter correct Password')
        else:
            raise ValidationError('enter correct username.')
    else:
        return render(request, 'tutionadmin/adminlogin.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = MainAdminRegisterForm(request.POST)
        if form.is_valid():
            password = request.POST.get('password')
            password1 = make_password(password)
            username = request.POST.get('username')
            MainAdminRegister(username=username,
                              password=password1).save()
            return HttpResponse('Welcome Admin')
        else:
            return HttpResponse(form.errors)
    else:
        form = MainAdminRegisterForm()
        return render(request, 'tutionadmin/adminregister.html', {'form': form})


# @login_required(login_url='tutionadmin:login')
def Adminhome(request):
    courses = AddCourse.objects.all()

    # list of registered courses
    # update course info and delete course info
    return render(request, 'tutionadmin/admin_home.html', {'courses': courses})


# def update(request):
#     queryset = AddCourse.objects.filter(id=id)
#     print(queryset)
#     form = AddCourseForm()
#     return render(request, 'tutionadmin/update.html', {'course': form})

class Update(UpdateView):
    model = AddCourse
    template_name = 'tutionadmin/update.html'
    form_class = AddCourseForm
    success_url = reverse_lazy('tutionadmin:adminhome')
#  It is useful for when you need to use a URL reversal before your project’s URLConf is loaded.
# Some common cases where this function is necessary are:
# providing a reversed URL as the url attribute of a generic class-based view
class Delete(DeleteView):
    model = AddCourse
    template_name = 'tutionadmin/delete.html'
    success_url = reverse_lazy('tutionadmin:adminhome')


def logout(request):
    return redirect('tutionadmin:login')

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, students!!!</title>
</head>
<body>
{% include 'basenavbar.html' %}
{% block content %}

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/basenavbar.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <a class="navbar-brand" href="{% url 'home' %}">Dev</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'tutionadmin:login' %}">Admin</a>
                        <a class="dropdown-item" href="#">Contact Us</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Register Here</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>

templates/course_detail_view.html
{% extends 'base.html' %}
{% block content %}
    <div class="container col-lg-4 my-5">
        <div class="card text-center">
            <div class="card-header">
                <h2 class="text-success">{{ object.course }}</h2>
            </div>
            <div class="card-body">
                <h5 class="card-title">Special Offers On Early Enrollment</h5>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam animi assumenda
                    at delectus ducimus eos explicabo impedit ipsum, nobis odit, perferendis quaerat quo similique
                    voluptatibus!</p>
                <a href="#" class="btn btn-primary">Enroll Now</a>
            </div>
            <div class="card-footer text-muted">
                <span>2 days ago</span>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% for object in object_list %}
        <div class="container col-lg-4 my-4">
            <div class="card" style="width: 18rem;">
                <div class="card-header" style="background-color: #83abf1">
                    {{ object.course }}
                </div>
                <div class="card-body">
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus est illo
                        ratione recusandae repellat sed voluptas. A aspernatur consequatur cum iste, magnam porro quasi
                        voluptatem.</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'detail' pk=object.courseid %}" class="btn btn-outline-info">Veiw</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/tutionadmin/admin_home.html
{% extends 'base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container col-lg-4 mx-auto">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">list of courses</li>
                <li class="breadcrumb-item"><a href="{% url 'tutionadmin:addcourse' %}">Add New Course</a></li>
                <li class="breadcrumb-item"><a href="{% url 'tutionadmin:logout' %}">Logout</a></li>
            </ol>
        </nav>
    </div>

    <div class="container">
        <table class="table table-striped">
        <thead class="thead-light">
            <tr>
                <th>Course</th>
                <th>Faculty</th>
                <th>Date</th>
                <th>Time</th>
                <th>Duration</th>
                <th>Fee</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            </thead>
        <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course }}</td>
                    <td>{{ course.faculty }}</td>
                    <td>{{ course.date }}</td>
                    <td>{{ course.time }}</td>
                    <td>{{ course.duration }}</td>
                    <td>{{ course.fee }}</td>
                    <td><a class="btn btn-warning btn-sm" href="{% url 'tutionadmin:update' pk=course.courseid %}">Update</a></td>
                    <td><a class="btn btn-danger btn-sm" href="{% url 'tutionadmin:delete' pk=course.courseid %}" >Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    {#        <p>add new course</p>#}
    {#        <p>list of courses</p>#}
    {#        <p>list of Students</p>#}
    {#        <p>upadate course</p>#}
    {#        <p>delete course</p>#}
    {#        <p>logout</p>#}

{% endblock %}

templates/tutionadmin/adminlogin.html
{% extends 'base.html' %}
 {% block content %}
     {% load crispy_forms_tags %}
     <div class="container mx-auto">
         <form  method="post">
             {% csrf_token %}
             {{ form|crispy }}
             <button class="btn btn-outline-info" type="submit">Log-in</button>
             <p class="my-2"><small class="small">New Staff?<a class='mx-2' href="{% url 'tutionadmin:register' %}">Sign-Up</a></small></p>
         </form>
     </div>
 {% endblock %}

templates/tutionadmin/adminregister.html
{% extends 'base.html' %}
 {% block content %}
     {% load crispy_forms_tags %}
     <div class="container col-lg-4 mx-auto">
         <form method="post">
             {% csrf_token %}
             {{ form|crispy }}
             <button class="btn btn-outline-info" type="submit">Submit</button>
         </form>
     </div>
 {% endblock %}

templates/tutionadmin/delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container col-lg-4 mx-auto " style="padding-top: 50px">
        <div class="card">
            <div class="card-header text-warning">
                <h3>Delete Course</h3>
            </div>
            <div class="card-body">
                <h5 class="card-title">are you sure you want to delete "{{ object.course }}" course?</h5>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" value="confirm" class="btn btn-danger">Yes,Delete</button>
                    <a class="btn btn-secondary mx-3" href="{% url 'tutionadmin:adminhome' %}">Cancle</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/tutionadmin/registercourse.html
{% extends 'base.html' %}
 {% block content %}
     {% load crispy_forms_tags %}
     <div class="container mx-auto">
         <form method="post">
             {% csrf_token %}
             {{ form|crispy }}
             <button class="btn btn-outline-info" type="submit">Add Course</button>
         </form>
     </div>
 {% endblock %}

templates/tutionadmin/update.html
{% extends 'base.html' %}
 {% block content %}
     {% load crispy_forms_tags %}
     <div class="container col-lg-4 mx-auto">
         <form method="post">
             {% csrf_token %}
             {{ form|crispy }}
             <button class="btn btn-outline-info" type="submit">Submit</button>
         </form>
     </div>
 {% endblock %}